[[plugins]]
repo = 'arcticicestudio/nord-vim'

[[plugins]]
repo = 'szw/vim-tags'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'junegunn/vim-easy-align'

[[plugins]]
repo = 'ntpeters/vim-better-whitespace'

[[plugins]]
repo = 'godlygeek/tabular'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'tpope/vim-pathogen'

[[plugins]]
repo = 'vim-syntastic/syntastic'

[[plugins]]
repo = 'lambdalisue/fern.vim'
