[[plugins]]
repo = 'arcticicestudio/nord-vim'

[[plugins]]
repo = 'delphinus/vim-auto-cursorline'

[[pluguins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'junegunn/vim-easy-align'

[[plugins]]
repo = 'ntpeters/vim-better-whitespace'

[[plugins]]
repo = 'godlygeek/tabular'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'tpope/vim-pathogen'

[[plugins]]
repo = 'vim-syntastic/syntastic'

[[plugins]]
repo = 'lambdalisue/fern.vim'

[[repo]]
repo = 'neoclide/coc.nvim'
rev = 'release'

[[plugins]]
repo = 'LnL7/vim-nix'

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'
on = 'NERDTreeToggle'

[[plugins]]
repo = 'neoclide/coc.nvim',
do = coc#util#install()

