[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'szw/vim-tags'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'junegunn/vim-easy-align'

[[plugins]]
repo = 'dag/vim-fish'

[[plugins]]
repo = 'ntpeters/vim-better-whitespace'

[[plugins]]
repo = 'godlygeek/tabular'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev  = 'release'

[[plugins]]
repo = 'tpope/vim-pathogen'
