[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1

[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'elixir-lang/vim-elixir'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'vim-ruby/vim-ruby'

[[plugins]]
repo = 'Shougo/vimfiler.vim'

[[plugins]]
repo = 'scrooloose/syntastic'
on_ft = ['python', 'javascript']

[[plugins]]
repo = 'vim-erlang/vim-erlang-runtime'
[[plugins]]
repo = 'vim-erlang/vim-erlang-omnicomplete'
[[plugins]]
repo = 'vim-erlang/vim-erlang-compiler'
[[plugins]]
repo = 'vim-erlang/vim-erlang-tags'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'slashmili/alchemist.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'racer-rust/vim-racer'

[[plugins]]
repo = 'rust-lang/rust.vim'

[[plugins]]
repo = 'OmniSharp/omnisharp-vim'
build = 'xbuild server/OmniSharp.sln'
on_ft = ['csharp']

[[plugins]]
repo = 'nvie/vim-flake8'
on_ft = 'python'

[[plugins]]
repo = 'kballard/vim-swift'

[[plugins]]
repo = 'keith/swift.vim'

[[plugins]]
repo = 'udalov/kotlin-vim'
