[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'Shougo/dein.vim'
on_cmd = 'Denite'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1

[[plugins]]
repo = 'szw/vim-tags'

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'

[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'

[[plugins]]
repo = 'Shougo/vimfiler.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'elixir-lang/vim-elixir'

[[plugins]]
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'vim-ruby/vim-ruby'

[[plugins]]
repo = 'scrooloose/syntastic'
on_ft = ['python', 'javascript', 'elixir']

[[plugins]]
repo = 'vim-erlang/vim-erlang-runtime'

[[plugins]]
repo = 'vim-erlang/vim-erlang-omnicomplete'

[[plugins]]
repo = 'vim-erlang/vim-erlang-compiler'

[[plugins]]
repo = 'vim-erlang/vim-erlang-tags'

[[plugins]]
repo = 'slashmili/alchemist.vim'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'racer-rust/vim-racer'

[[plugins]]
repo = 'rust-lang/rust.vim'

[[plugins]]
repo = 'nvie/vim-flake8'
on_ft = 'python'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'vim-jp/vim-cpp'

[[plugins]]
repo = 'rizzatti/dash.vim'

[[plugins]]
repo = 'airblade/vim-rooter'

[[plugins]]
repo = 'junegunn/vim-easy-align'

[[plugins]]
repo = 'dag/vim-fish'

[[plugins]]
repo = 'reasonml-editor/vim-reason-plus'

[[plugins]]
repo = 'kien/rainbow_parentheses.vim'

[[plugins]]
repo = 'ntpeters/vim-better-whitespace'
