[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = 'javascript'

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = 'ruby'

[[plugins]]
repo = 'elixir-lang/vim-elixir'
on_ft = 'elixir'

[[plugins]]
repo = 'slashmili/alchemist.vim'
on_ft = 'elixir'

[[plugins]]
repo = 'vim-erlang/vim-erlang-runtime'
on_ft = 'erlang'

[[plugins]]
repo = 'vim-erlang/vim-erlang-omnicomplete'
on_ft = 'erlang'

[[plugins]]
repo = 'vim-erlang/vim-erlang-compiler'
on_ft = 'erlang'

[[plugins]]
repo = 'vim-erlang/vim-erlang-tags'
on_ft = 'erlang'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repo = 'racer-rust/vim-racer'
on_ft = 'rust'

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'

[[plugins]]
repo = 'nvie/vim-flake8'
on_ft = 'python'

[[plugins]]
repo = 'lambdalisue/vim-django-support'
on_ft = 'python'

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'

[[plugins]]
repo = 'JulesWang/css.vim'
on_ft = 'css'

[[plugins]]
repo = 'cakebaker/scss-syntax.vim'
on_ft = 'scss'

[[plugins]]
repo = 'vim-scripts/nginx.vim'
on_ft = 'nginx'

[[plugins]]
repo = 'vim-jp/cpp-vim'
on_ft = 'cpp'

[[plugins]]
repo = 'Quramy/tsuquyomi'
on_ft = 'typescript'

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = 'typescript'

[[plugins]]
repo = 'posva/vim-vue'
on_ft = 'vue'

[[plugins]]
repo = 'flowtype/vim-flow'
on_ft = 'javascript'

[[plugins]]
repo = 'prettier/vim-prettier'
on_ft = ['javascript']

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'justmao945/vim-clang'
on_ft  =  ['c', 'cpp']
