#!/bin/bash
ELIXIR_VERSION="v1.6.6"
ELIXIR_DOWNLOAD_URL="https://github.com/elixir-lang/elixir/archive/${ELIXIR_VERSION}.tar.gz"

rm -rf ~/packages/elixir
mkdir ~/packages/elixir
curl -fSL -o elixir-src.tar.gz $ELIXIR_DOWNLOAD_URL
tar -xzC ~/packages/elixir --strip-components=1 -f elixir-src.tar.gz
rm elixir-src.tar.gz
cd ~/packages/elixir
make install clean
